


export default  class CommonConstant{
  /**
   * Full width or height.
   */
  static readonly FULL_LENGTH: string = '100%';

  /**
   * Title height.
   */
  static readonly TITLE_WIDTH: string = '80%';

  /**
   * List default width.
   */
  static readonly LIST_DEFAULT_WIDTH: string = '93.3%';

  /**
   * Opacity of default.
   */
  static readonly OPACITY_DEFAULT: number = 1;

  /**
   * Opacity of default.
   */
  static readonly OPACITY_COMPLETED: number = 0.4;

  /**
   * BorderRadius of list item.
   */
  static readonly BORDER_RADIUS: number = 24;

  /**
   * BorderRadius of list item.
   */
  static readonly FONT_WEIGHT: number = 500;

  /**
   * Space of column.
   */
  static readonly COLUMN_SPACE: number = 16;
  /**
   * The second page url.
   */
  static readonly SECOND_URL: string = 'pages/ToDoListPage';

  /**
   * The Login page url.
   */
  static readonly LOGIN_URL: string = 'pages/LoginPage';

  /**
   * default click index.
   */
  static readonly DEFAULT_CLICK_INDEX: number = -1;
  /**
   * The targer manager page url.
   */
  static readonly TARGET_MANAGER_PAGE: string = 'pages/TargetManagerPage';
  /**
   * The Main page url
   */
  static readonly MAIN_URL:string='pages/MainPage';
  /**
   * The second page message.
   */
  static readonly SECOND_MESSAGE: string = 'Second Page';
  /**
   * The width or height of the component is spread across the parent component.
   */
  static readonly FULL_PARENT = '100%';
   /**
    * 满屏宽度
    */
  static readonly FULL_WIDTH='100%'
  /**
   * 首页的column间距
   */
  static readonly INDEX_COLUMN_SPACE=10;
  /**
   * Input length of the account.
   */
  static readonly INPUT_ACCOUNT_LENGTH = 11;
  /**
   *  Left padding of the input box
   */
  static readonly INPUT_PADDING_LEFT = 0;
  /**
   *  Input length of the password.
   */
  static readonly INPUT_PASSWORD_LENGTH = 8;
  /**
   * The width of button
   */
  static readonly BUTTON_WIDTH = '90%';
  /**
   * Delay time of simulated login
   */
  static readonly LOGIN_DELAY_TIME = 2000;
  /**
   * Spacing of other login methods
   */
  static readonly LOGIN_METHODS_SPACE = 44;
  /**
   * Home tab index
   */
  static readonly HOME_TAB_INDEX = 0;

  /**
   * Mine tab index
   */
  static readonly MINE_TAB_INDEX = 1;
  /**
   * Title text of the home page
   */
  static readonly HOME_TITLE = '首页';

  /**
   * Title text of the setting page
   */
  static readonly MINE_TITLE = '我的';
  /**
   * Common Spacing of Components
   */
  static readonly COMMON_SPACE = 12;
  /**
   * The width of setting list
   */
  static readonly SET_LIST_WIDTH = '42%';
  /**
   * Larger font weight.
   */
  static readonly FONT_WEIGHT_LARGE: number = 700;
  /**
   * Radius of bookInfo area.
   */
  static readonly IMAGE_BORDER_RADIUS: number = 12;

  /**
   * Opacity of text.
   */
  static readonly OPACITY: number = 0.4;

  /**
   * Margin left of book item.
   */
  static readonly TARGET_MARGIN_LEFT: string = '5%';
  /**
   * Default progress value.
   */
  static readonly DEFAULT_PROGRESS_VALUE: string = '-';
  /**
   * Width of slider.
   */
  static readonly STROKE_WIDTH: number = 4.8;
  /**
   * Width of the content area.
   */
  static readonly MAIN_BOARD_WIDTH: string = '93.3%';

  /**
   * Radius of bookInfo area.
   */
  static readonly TARGET_BORDER_RADIUS: number = 24;
  /**
   * Full height.
   */
  static readonly FULL_HEIGHT: string = '100%';
  /**
   * Width of checkbox.
   */
  static readonly CHECKBOX_WIDTH: number = 20;

  /**
   * list space.
   */
  static readonly LIST_SPACE: number = 12;

  /**
   * Width of task item.
   */
  static readonly TASK_NAME_WIDTH: string = '30%';
  /**
   * Max of line.
   */
  static readonly MAX_LINES: number = 2;
  /**
   * The smallest value of slider.
   */
  static readonly SLIDER_MIN_VALUE: number = 0;
  /**
   * The maximum value of slider.
   */
  static readonly SLIDER_MAX_VALUE: number = 100;
  /**
   * Step of slider.
   */
  static readonly SLIDER_STEP: number = 1;
  /**
   * Margin top of slider button.
   */
  static readonly SLIDER_INNER_WIDTH: string = '90%';
  /**
   * Width of slider.
   */
  static readonly SLIDER_WIDTH: string = '90%';
  /**
   * Height of slider.
   */
  static readonly SLIDER_HEIGHT: string = '20%';
  /**
   * Radius of list.
   */
  static readonly LIST_RADIUS: number = 24;
  /**
   * Margin top of slider button.
   */
  static readonly SLIDER_BUTTON_MARGIN: string = '4%';
  /**
   * Button width of dialog.
   */
  static readonly DIALOG_OPERATION_WIDTH: string = '70%';
  /**
   * Button height of dialog.
   */
  static readonly DIALOG_OPERATION_HEIGHT: string = '10%';
  /**
   * Width of dialog.
   */
  static readonly DIALOG_WIDTH: string = '90.3%';
  /**
   * Radius of dialog.
   */
  static readonly DIALOG_BORDER_RADIUS: number = 32;
  /**
   * Current month plus one.
   */
  static readonly PLUS_ONE: number = 1;

  /**
   * The fraction or number of seconds is less than 10.
   */
  static readonly TEN: number = 10;
  /**
   * x-axis transition animation.
   */
  static readonly TRANSITION_ANIMATION_X: number = 1;

  /**
   * y-axis transition animation.
   */
  static readonly TRANSITION_ANIMATION_Y: number = 0;
  /**
   * Opacity of not.
   */
  static readonly NO_OPACITY: number = 1;

  /**
   * default SliderChangeMode.
   */
  static readonly DEFAULT_SLIDER_MODE: number = -1;

  /**
   * click SliderChangeMode.
   */
  static readonly CLICK_SLIDER_MODE: number = 3;

  /**
   * Height of list.
   */
  static readonly LIST_HEIGHT: string = '80%';
  /**
   * One task of data.
   */
  static readonly ONE_TASK: number = 1;
  /**
   * Height of list board.
   */
  static readonly LIST_BOARD_HEIGHT: string = '67%';
  /**
   * Button height of dialog.
   */
  static readonly DIALOG_INPUT_HEIGHT: string = '40%';
  /**
   * Input margin of dialog.
   */
  static readonly DIALOG_INPUT_MARGIN: string = '6%';
  /**
   * Bottom toast.
   */
  static readonly TOAST_MARGIN_BOTTOM: number = 64;

  /**
   * Horizontal offset of dialog.
   */
  static readonly DIALOG_OFFSET_X: number = 0;
  /**
   * Toast Duration.
   */
  static readonly TOAST_TIME: number = 3000;
  /**
   * animation duration.
   */
  static readonly DURATION: number = 300;
  static readonly TODO_DATA:Array<string>=[
    "早起锻炼","准备早餐","阅读名著","学习ArkTs","看剧放松"
  ]

}